echo Certificate Batch for create and upload certificate image
gulp CreateCertificate --option algorithm-ch
gulp CreateCertificate --option angular
gulp CreateCertificate --option bk_android_1
gulp CreateCertificate --option bk_android_2
gulp CreateCertificate --option bk_android_3
gulp CreateCertificate --option bk_android_4
gulp CreateCertificate --option bk_android_5
gulp CreateCertificate --option bk_android_6
gulp CreateCertificate --option bk_caffe_1
gulp CreateCertificate --option bk_caffe_2
gulp CreateCertificate --option bk_caffe_3
gulp CreateCertificate --option bk_caffe_4
gulp CreateCertificate --option bk_csharp_1
gulp CreateCertificate --option bk_csharp_10
gulp CreateCertificate --option bk_csharp_11
gulp CreateCertificate --option bk_csharp_12
gulp CreateCertificate --option bk_csharp_13
gulp CreateCertificate --option bk_csharp_14
gulp CreateCertificate --option bk_csharp_15
gulp CreateCertificate --option bk_csharp_16
gulp CreateCertificate --option bk_csharp_17
gulp CreateCertificate --option bk_csharp_18
gulp CreateCertificate --option bk_csharp_19
gulp CreateCertificate --option bk_csharp_2
gulp CreateCertificate --option bk_csharp_3
gulp CreateCertificate --option bk_csharp_4
gulp CreateCertificate --option bk_csharp_5
gulp CreateCertificate --option bk_csharp_6
gulp CreateCertificate --option bk_csharp_7
gulp CreateCertificate --option bk_csharp_8
gulp CreateCertificate --option bk_csharp_9
gulp CreateCertificate --option bk_cuda_1
gulp CreateCertificate --option bk_cuda_2
gulp CreateCertificate --option bk_cuda_3
gulp CreateCertificate --option bk_cudnn_1
gulp CreateCertificate --option bk_cudnn_2
gulp CreateCertificate --option bk_cudnn_3
gulp CreateCertificate --option bk_db2_1
gulp CreateCertificate --option bk_db2_2
gulp CreateCertificate --option bk_dlbook_1
gulp CreateCertificate --option bk_dlbook_2
gulp CreateCertificate --option bk_dlbook_3
gulp CreateCertificate --option bk_dlbook_4
gulp CreateCertificate --option bk_dlbook_5
gulp CreateCertificate --option bk_dlbook_6
gulp CreateCertificate --option bk_dlbook_7
gulp CreateCertificate --option bk_dlbook_8
gulp CreateCertificate --option bk_docker_1
gulp CreateCertificate --option bk_docker_2
gulp CreateCertificate --option bk_go_1
gulp CreateCertificate --option bk_gpu_1
gulp CreateCertificate --option bk_gpu_2
gulp CreateCertificate --option bk_gpu_3
gulp CreateCertificate --option bk_gpu_4
gulp CreateCertificate --option bk_js_1
gulp CreateCertificate --option bk_js_2
gulp CreateCertificate --option bk_js_3
gulp CreateCertificate --option bk_js_4
gulp CreateCertificate --option bk_js_5
gulp CreateCertificate --option bk_kubernetes_1
gulp CreateCertificate --option bk_kubernetes_2
gulp CreateCertificate --option bk_kubernetes_3
gulp CreateCertificate --option bk_kubernetes_4
gulp CreateCertificate --option bk_kubernetes_5
gulp CreateCertificate --option bk_kubernetes_6
gulp CreateCertificate --option bk_objectc_1
gulp CreateCertificate --option bk_objectc_2
gulp CreateCertificate --option bk_objectc_3
gulp CreateCertificate --option bk_objectc_4
gulp CreateCertificate --option bk_objectc_5
gulp CreateCertificate --option bk_objectc_6
gulp CreateCertificate --option bk_openshift_1
gulp CreateCertificate --option bk_openshift_2
gulp CreateCertificate --option bk_openshift_3
gulp CreateCertificate --option bk_oracle_1
gulp CreateCertificate --option bk_oracle_2
gulp CreateCertificate --option bk_oracle_3
gulp CreateCertificate --option bk_oracle_4
gulp CreateCertificate --option bk_oracle_5
gulp CreateCertificate --option bk_oracle_6
gulp CreateCertificate --option bk_oracle_7
gulp CreateCertificate --option bk_paddle_1
gulp CreateCertificate --option bk_python_1
gulp CreateCertificate --option bk_python_10
gulp CreateCertificate --option bk_python_11
gulp CreateCertificate --option bk_python_12
gulp CreateCertificate --option bk_python_2
gulp CreateCertificate --option bk_python_3
gulp CreateCertificate --option bk_python_4
gulp CreateCertificate --option bk_python_5
gulp CreateCertificate --option bk_python_6
gulp CreateCertificate --option bk_python_7
gulp CreateCertificate --option bk_python_8
gulp CreateCertificate --option bk_python_9
gulp CreateCertificate --option bk_ruby_1
gulp CreateCertificate --option bk_ruby_2
gulp CreateCertificate --option bk_ruby_3
gulp CreateCertificate --option bk_ruby_4
gulp CreateCertificate --option bk_ruby_5
gulp CreateCertificate --option bk_ruby_6
gulp CreateCertificate --option bk_shell_1
gulp CreateCertificate --option bk_shell_2
gulp CreateCertificate --option bk_shell_3
gulp CreateCertificate --option bk_shell_4
gulp CreateCertificate --option bk_swift_1
gulp CreateCertificate --option bk_swift_2
gulp CreateCertificate --option bk_swift_3
gulp CreateCertificate --option bk_swift_4
gulp CreateCertificate --option bk_tensorflow_1
gulp CreateCertificate --option bk_tensorflow_2
gulp CreateCertificate --option bk_tensorflow_3
gulp CreateCertificate --option bk_tensorflow_4
gulp CreateCertificate --option bk_tensorrt_1
gulp CreateCertificate --option bk_tensorrt_2
gulp CreateCertificate --option browser-ch
gulp CreateCertificate --option cluster
gulp CreateCertificate --option cordova
gulp CreateCertificate --option create-powershell-scripts
gulp CreateCertificate --option database
gulp CreateCertificate --option dataStruct-zh
gulp CreateCertificate --option debugging-powershell
gulp CreateCertificate --option designpattern
gulp CreateCertificate --option distribute
gulp CreateCertificate --option docker
gulp CreateCertificate --option DockerManual
gulp CreateCertificate --option firebase
gulp CreateCertificate --option forcsharpbeginner
gulp CreateCertificate --option framework-zh
gulp CreateCertificate --option framework7
gulp CreateCertificate --option git-zh
gulp CreateCertificate --option git
gulp CreateCertificate --option gulp
gulp CreateCertificate --option hello_minikube
gulp CreateCertificate --option How-to-use-your-time-correctly
gulp CreateCertificate --option http-live-streaming
gulp CreateCertificate --option http
gulp CreateCertificate --option hybriddev
gulp CreateCertificate --option java
gulp CreateCertificate --option js
gulp CreateCertificate --option kubernetes_steps
gulp CreateCertificate --option linux
gulp CreateCertificate --option lohmd2n
gulp CreateCertificate --option maven
gulp CreateCertificate --option mklite
gulp CreateCertificate --option mp-zh
gulp CreateCertificate --option mysql
gulp CreateCertificate --option network-zh
gulp CreateCertificate --option oop
gulp CreateCertificate --option openshift
gulp CreateCertificate --option oracle
gulp CreateCertificate --option performance-zh
gulp CreateCertificate --option powershell-beginners-guide
gulp CreateCertificate --option python
gulp CreateCertificate --option queue
gulp CreateCertificate --option redis
gulp CreateCertificate --option regex
gulp CreateCertificate --option socket
gulp CreateCertificate --option springboot
gulp CreateCertificate --option springframework
gulp CreateCertificate --option sql
gulp CreateCertificate --option systemdesign
gulp CreateCertificate --option tensorflowjs
gulp CreateCertificate --option vue-infinite-loading
gulp CreateCertificate --option vue
gulp CreateCertificate --option working-with-powershell-objects
gulp CreateCertificate --option 人工智能数学基础
gulp CreateCertificate --option lohguildline
gulp CreateCertificate --option release_android
gulp CreateCertificate --option release_windows
gulp CreateCertificate --option release_ios
